# Generated by Django 2.1.5 on 2019-01-15 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('price', models.IntegerField()),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodapp.Restaurant')),
            ],
            options={
                'db_table': 'restaurant_product',
            },
        ),
        migrations.AddField(
            model_name='userrestaurantdefaultpreference',
            name='products',
            field=models.ManyToManyField(to='foodapp.RestaurantProduct'),
        ),
    ]
