# Generated by Django 2.1.5 on 2019-01-15 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0002_auto_20190115_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantproduct',
            name='description',
            field=models.CharField(default='', max_length=2048),
            preserve_default=False,
        ),
    ]
